### ISSUE TITLE
{application_name} included in URL

### ISSUE THREAD

**Issue by nvembar** [GSA/api-standards#20]
Do we have a good sense of whether this is a good idea - that is, are we exposing backend concerns on the frontend? 

Should we instead look to the business function + noun to be unique across applications?

**Comment by rdgsa** [comment]
I agree that application name may be too much of a backend concern. However, I am not certain that currently in GSA we can differentiate all the potential APIs with only business function and noun. 

I think we will end up trying to force one of those two things to be less generic than they should ideally be.

For instance, it is possible that more than one API might be provided containing vendors even under a major business function such as "acquisitions".

Another example is City Pairs: we have a business function of "travel" and a noun of "airfares" (and "fares" would have been another option). However if another type of airfare were shared under the travel section, it would need to be differentiated somehow.

So based on this, I think we need a second-level differentiator for the necessary context. I think that application is probably very simple to use today. And maybe in the future a second-level taxonomy term could provide that function.

**Comment by nvembar** [comment]
All good points. I think keeping as is makes sense and we should consider the taxonomy around this something to mature over time.
