### ISSUE TITLE
Publish the standards on .gov web site

### ISSUE THREAD

**Issue by rdgsa** [GSA/api-standards#23]
Add capability to publish this content on GSA site, such as tech.gsa.gov.

**Comment by gbinal** [comment]
Just curious, but why?  

For standards that have a technical audience like this, I've always found the readme on a repo's home page to be more than sufficient, and sometimes even superior.  

https://github.com/GSA/api-standards#readme works does the job well and keeps you from creating duplicate content.

**Comment by jcastle** [comment]
@rdgsa, was thinking the same as @gbinal on this one.  Why duplicate?  We can point [here](https://github.com/GSA/api-standards) (as we do) from open.gsa.gov/api.

**Comment by jcastle** [comment]
Motion to close issue #23 (this one).

**Comment by rdgsa** [comment]
I believe this was a @nvembar request. I am very comfortable with the current.

**Comment by nvembar** [comment]
I'm ok with closing this as long as we have a reference to it on tech.gsa.gov.

**Comment by rdgsa** [comment]
Closing this one.

**Comment by jcastle** [comment]
Lets leave this open until we have a chance to update tech.gsa.gov with a link.  I think we could put a link in a couple of the API guides.

**Comment by jcastle** [comment]
@nvembar, we have an [API Standards guide](https://tech.gsa.gov/guides/API_standards/) on tech.gsa.gov.
