### ISSUE TITLE
Take off the "draft" in the label

### ISSUE THREAD

**Issue by rdgsa** [GSA/api-standards#30]
Need to determine when to take "draft" off of the standards and the references to them on tech.gsa.gov.

A conversation probably needs to occur regarding the process for removing that label and what it signifies.

**Comment by gbinal** [comment]
I def. think it's worth removing 'draft' at some point.  If you want to be cautious and incremental, you could add a 'beta' to them and also a one sentence note at the beginning or end that says a bit of where they are/what they aren't.

**Comment by jcastle** [comment]
Updated from DRAFT to BETA and added Notes.
