### ISSUE TITLE
Update link to GSA API directory repo

### ISSUE THREAD

**Issue by rdgsa** [GSA/api-standards#4]
The standards explain that the process for adding an API to the directory involves the github repo of the open.gsa.gov web site. There is a current redesign of that site underway with a separate repo.

When the new open.gsa.gov site goes live, update the repo name in the API Standards.

**Comment by rdgsa** [comment]
@saracope Do you know if we will be renaming the repo for open.gsa.gov? I want to point them to it in the standards for adding to the API directory. Currently the repo is open-gsa-redesign.

**Comment by rdgsa** [comment]
Also need to review the link to open.gsa.gov/developer.

**Comment by jcastle** [comment]
Should probably have open.gsa.gov/developer point to open.gsa.gov, the redesigned site.  Not sure why we take it to the repo.  Used to go to the API page but really a developer could be there for data, APIs, and/or code.

**Comment by rdgsa** [comment]
I thought this had been fixed on this issue.

https://github.com/GSA/open-gsa-redesign/issues/79

The redirect may have been lost.

**Comment by jcastle** [comment]
Reopened on https://github.com/GSA/open-gsa-redesign/issues.  Will put in a pull request when I have a min to update.

**Comment by gbinal** [comment]
Thanks for catching this.  I'd noticed the same last week and meant to follow up.  Also, don't forget to also redirect open.gsa.gov/developers along with open.gsa.gov/developer.  It's worth having both in place and going to the right place.

**Comment by jcastle** [comment]
Submitted to open.gsa.gov site issue #114
